config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "reservations#index"
  resources :reservations
end

# == Route Map
#

app/models/ConstData.rb
# Singletonは、Mix-inしたクラスのinstanceは同一のインスタンスを返すようになる
require 'singleton'

# シングルトン
class ConstData
  # instanceメソッドが定義され、newメソッドがprivateに設定される
  include Singleton
  attr_accessor :pet_types
  attr_accessor :hospitals
  attr_accessor :diseases

  def initialize
    @pet_types = nil
    @hospitals = nil
    @diseases = nil
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disease.rb
class Disease < ApplicationRecord
  belongs_to :reservation
end

# == Schema Information
#
# Table name: diseases
#
#  id             :bigint           not null, primary key
#  disease_name   :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  reservation_id :bigint
#
# Indexes
#
#  index_diseases_on_reservation_id  (reservation_id)
#
# Foreign Keys
#
#  fk_rails_...  (reservation_id => reservations.id)
#

app/models/hospital.rb
class Hospital < ApplicationRecord
  belongs_to :reservation
end

# == Schema Information
#
# Table name: hospitals
#
#  id             :bigint           not null, primary key
#  hospital_name  :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  reservation_id :bigint
#
# Indexes
#
#  index_hospitals_on_reservation_id  (reservation_id)
#
# Foreign Keys
#
#  fk_rails_...  (reservation_id => reservations.id)
#

app/models/pet_type.rb
class PetType < ApplicationRecord
  belongs_to :reservation
end

# == Schema Information
#
# Table name: pet_types
#
#  id             :bigint           not null, primary key
#  type_name      :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  reservation_id :bigint
#
# Indexes
#
#  index_pet_types_on_reservation_id  (reservation_id)
#
# Foreign Keys
#
#  fk_rails_...  (reservation_id => reservations.id)
#

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id             :bigint           not null, primary key
#  comment        :string(255)
#  delete_flg     :string(255)
#  end_date       :datetime
#  pet_name       :string(255)
#  reg_date       :datetime
#  start_date     :datetime
#  update_date    :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  disease_id     :bigint
#  hospital_id    :bigint
#  reg_user_id    :bigint
#  type_id        :bigint
#  update_user_id :bigint
#
class Reservation < ApplicationRecord
  has_many :reservation_images, dependent: :destroy
  accepts_nested_attributes_for :reservation_images, 
  allow_destroy: true
  has_one :pet_type
  has_one :hospital
  has_one :disease
end

app/models/reservation_image.rb
# == Schema Information
#
# Table name: reservation_images
#
#  id             :bigint           not null, primary key
#  src            :string(255)      not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  reservation_id :bigint           not null
#
# Indexes
#
#  index_reservation_images_on_reservation_id  (reservation_id)
#
# Foreign Keys
#
#  fk_rails_...  (reservation_id => reservations.id)
#
class ReservationImage < ApplicationRecord
  belongs_to :reservation
  mount_uploader :src, ReservationImageUploader
  validates :src, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
    @reservation_files = @reservation.reservation_images.build
    @pet_types = ConstData.instance.pet_types
    @hospitals = ConstData.instance.hospitals
    @diseases = ConstData.instance.diseases
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      # 画像が投稿されていないパターンもあるので条件分岐
      if params[:reservation_images].present?
        # フォームで入力されたファイルを一つずつレコードに格納していく
        params[:reservation_images][:src].each do |file|
          @reservation_file = @reservation.reservation_images.new(src: file, reservation_id: @reservation.id)
          @reservation_file.save
        end


      end
      redirect_to reservation_path(@reservation)
    # 投稿が失敗した場合
    else
      @reservations = Reservation.all
      redirect_to reservations_path
    end
  end
 
  def show
    @reservation = Reservation.find(params[:id])
    @reservation_files = ReservationImage.where(reservation_id: @reservation.id)
  end

  def reservation_params 
    params.require(:reservation).permit(:pet_name,:comment,:hospital_id,:disease_id,:start_date,:end_date,reservation_images_attributes:[:src,:_destroy,:id])
  end
end

app/helpers/Hospital.rb
# Singletonは、Mix-inしたクラスのinstanceは同一のインスタンスを返すようになる
require 'singleton'

# シングルトン
class Hospital
  # instanceメソッドが定義され、newメソッドがprivateに設定される
  include Singleton
  attr_accessor :hospitals

  def initialize
    @hospitals = nil
  end
end

app/helpers/Hospitala.rb
# Singletonは、Mix-inしたクラスのinstanceは同一のインスタンスを返すようになる
require 'singleton'

# シングルトン
class Hospitala
  # instanceメソッドが定義され、newメソッドがprivateに設定される
  include Singleton
  attr_accessor :hospitals

  def initialize
    @hospitals = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetReserve</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.slim
.bg_container
  h3.page_heading 予約一覧
  = link_to '新規登録', new_reservation_path,class: 'common_btn'
  - @reservations.each do |reservation|
    = link_to reservation_path(reservation), class: 'block'
      .reservation_compo
        .card-header
          = reservation.pet_name
        .card-body
          p.card-text
            = reservation.comment

app/views/reservations/new.slim
.bg_container
  h3.page_heading 予約登録
  .bg_inner
    = form_with url: reservations_path, model: @reservation do |form|
      .form-group
        = form.label :pet_name, 'おなまえ'
        = form.text_field :pet_name, class: 'form-control'
      .form-group
        = form.label :reservation_images, '写真(複数枚登録できます)'
        = form.fields_for :reservation_images do |i|
          = i.file_field :src, multiple: true, name: "reservation_images[src][]"
      .form-group
        = form.label :pet_type_id, '種類'
        = form.select :pet_type_id,[["犬", "犬"], ["猫", "猫"], ["爬虫類", "爬虫類"]],{include_blank: '選択してください'}, class: 'form-control'
      .form-group
        = form.label :hospital_id, '施術院'
        = form.select :hospital_id,[["池袋院", "池袋院"], ["渋谷院", "渋谷院"], ["新宿院", "新宿院"]],{include_blank: '選択してください'}, class: 'form-control'
      .form-group
        = form.label :disease_id, '病状'
        = form.select :disease_id,[["嘔吐", "嘔吐"], ["腫れ", "腫れ"], ["外傷あり", "外傷あり"]],{include_blank: '選択してください'}, class: 'form-control'
      .input-group data-target-input="nearest" 
        = form.label :start_date, '施術開始時間'
        = form.text_field :start_date, id: "start_date", class: "form-control datepicker", data: { target: '#start_date'}
        .input-group-append data-target="#start_date" data-toggle="datetimepicker" 
          .input-group-text
            i.fa.fa-calendar
      .input-group data-target-input="nearest" 
        = form.label :end_date, '施術終了時間'
        = form.text_field :end_date, id: "end_date", class: "form-control datepicker", data: { target: '#end_date'}
        .input-group-append data-target="#end_date" data-toggle="datetimepicker" 
          .input-group-text
            i.fa.fa-calendar
      .form-group
        = form.label :comment, 'コメント'
        = form.text_area :comment, class: 'form-control'
      .betweenitems
        = link_to reservations_path,class: 'common_btn' 
          <p>戻る</p>
        = form.submit '登録', class: 'common_btn'
javascript: 
  $(function () {
    $('.datepicker').datetimepicker({
      format: 'YYYY-MM-DD HH:mm'
    });
  });
link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" /
/! Optional theme
link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" rel="stylesheet" /
link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" rel="stylesheet" /
script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js" 
script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" 
script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" 
script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js" 

app/views/reservations/show.slim
.bg_container
  h3.page_heading 予約詳細
  .bg_inner.my-4
    .compo_heading
      -p @reservation.pet_name
      p 2021/03/21 16:00 ~ 18:00
    .pet_main
      .pet_imgWrap
        - if @reservation_files.present?
          - @reservation_files.each do |file|
            img src=file.src.model.src
        - else 
          img src="/default.jpg"
      .pet_about
        p 種別 : 犬
        p 施術院 : 池袋院
        p 症状 : 嘔吐
    .card-body
      p.card-text
        = @reservation.comment
    .betweenitems
        = link_to reservations_path,class: 'common_btn' 
          <p>戻る</p>
        = link_to reservations_path,class: 'common_btn' 
          <p>戻る</p>